### ISSUE TITLE
problems running the scripts

### ISSUE THREAD

**Issue by dtrywets** [dinvlad/HyperVision#4]
Hey there, thanks for your great job towards Hyperion Webcam Capture.

sadly I have several issues getting the script running. 
please don't mind having me running this as root, as I don't care about this installation that much ;-) 

```
user@hyperion:~/HyperVision $ sudo -i
root@hyperion:~# cd /home/user/HyperVision/
root@hyperion:/home/user/HyperVision# python3 calibrate_camera.py -cm fisheye
Traceback (most recent call last):
  File "/home/user/HyperVision/calibrate_camera.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
root@hyperion:/home/user/HyperVision# pip3 install -r requirements.txt  --break-system-packages
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
  Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (41.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 MB 3.8 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.28.1)
Collecting screeninfo
  Downloading https://www.piwheels.org/simple/screeninfo/screeninfo-0.8.1-py3-none-any.whl (12 kB)
Collecting numpy>=1.21.2
  Downloading numpy-2.1.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 5.4 MB/s eta 0:00:00
Installing collected packages: screeninfo, numpy, opencv-python
Successfully installed numpy-2.1.3 opencv-python-4.10.0.84 screeninfo-0.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@hyperion:/home/user/HyperVision# python3 calibrate_camera.py -cm fisheye
Detected frame:  1 out of 20
Detected frame:  2 out of 20
Detected frame:  3 out of 20
Detected frame:  4 out of 20
Detected frame:  5 out of 20
Detected frame:  6 out of 20
Detected frame:  7 out of 20
Detected frame:  8 out of 20
Detected frame:  9 out of 20
Detected frame:  10 out of 20
Detected frame:  11 out of 20
Detected frame:  12 out of 20
Detected frame:  13 out of 20
Detected frame:  14 out of 20
Detected frame:  15 out of 20
Detected frame:  16 out of 20
Detected frame:  17 out of 20
Detected frame:  18 out of 20
Detected frame:  19 out of 20
Detected frame:  20 out of 20
Traceback (most recent call last):
  File "/home/user/HyperVision/calibrate_camera.py", line 324, in <module>
    main()
  File "/home/user/HyperVision/calibrate_camera.py", line 306, in main
    params = calibrate(
             ^^^^^^^^^^
  File "/home/user/HyperVision/calibrate_camera.py", line 277, in calibrate
    rms, k, d, _, _ = calib_func(
                      ^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) /io/opencv/modules/calib3d/src/fisheye.cpp:1502: error: (-3:Internal error) CALIB_CHECK_COND - Ill-conditioned matrix for input array 0 in function 'CalibrateExtrinsics'

root@hyperion:/home/user/HyperVision# ls
calibrate_camera.py  images	 __pycache__  requirements.txt
calibrate_screen.py  LICENSE.md  README.md    util.py
root@hyperion:/home/user/HyperVision# python3 calibrate_screen.py 
Traceback (most recent call last):
  File "/home/user/HyperVision/calibrate_screen.py", line 420, in <module>
    main()
  File "/home/user/HyperVision/calibrate_screen.py", line 380, in main
    cam = CameraParams.load(args.cam_params_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/HyperVision/util.py", line 88, in load
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'params.json'
```

could you please help me out on this one? I'm running the scripts on a Raspberry 4 with Hyperbian and GDM3.

thanks for your help :-)

**Comment by dtrywets** [comment]
after testing around a bit I found that not using ```-cm fisheye``` lets the script run successfully but screen calibration then errors. I tried patching around the code a little bit but am not familiar with used libs and functions. :-(

**Comment by dtrywets** [comment]
anyone alive here?
